# Generated by Django 5.1.4 on 2025-04-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
