# Generated by Django 5.1.4 on 2025-04-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
