# Generated by Django 5.1.4 on 2025-04-04 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
